### ISSUE TITLE
Can svelte-pixi work with rollup?

### ISSUE THREAD

**Issue by thismatters** [mattjennings/svelte-pixi#30]
I'm trying to use svelte-pixi with a rollup project and have hit a wall. Seemingly just having the line `import * as PIXI from 'pixi.js'` causes a syntax error in the built js bundle: `Uncaught SyntaxError: Unexpected identifier 'Object'`.

Do you have any advice for getting svelte-pixi working under rollup?

**Comment by mattjennings** [comment]
At one point I did have a rollup example and I remember it being pretty fussy. I've since removed it in favour of a Vite example, but you can see it [here](https://github.com/mattjennings/svelte-pixi/tree/112af1c953b6a85f78182b790da17dd70f715c1d/examples/rollup). It was from 2 years ago, so I'm not sure where it might stand with recent versions of rollup/pixi/svelte-pixi.

**Comment by thismatters** [comment]
Wow! Thank you!

That worked perfectly. The only change I made to my rollup.config.js was to add this portion to the `resolve` plugin:

```json
      preferBuiltins: false,
      dedupe: (importee) => {
        return importee === 'svelte' || importee.startsWith('svelte/')
      },
```
